apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.externalSecret.secretStoreRef }}
  target:
    name: {{ .Release.Name }}-secrets
  data:
    {{- range $k, $path := .Values.externalSecret.keys }}
    - secretKey: {{ $k }}
      remoteRef:
        key: {{ $path }}
    {{- end }}
